In [5]:
import tensorflow as tf
import numpy as np
from scipy.optimize import linear_sum_assignment

def box_cxcywh_to_xyxy(boxes_raw):
    """ 
    Helper function used to convert raw box output to the 
    top left and bottom right point of the box.
    
    Params:
    - boxes_raw: Tensor of shape (N, 4) containing N boxes in (center x, center y, width, height) format.

    Returns:
    - box_coords: Tensor of shape (N, 4) containing N boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.
    """
    cx, cy, w, h = tf.unstack(boxes_raw, axis=1)

    x_topleft = cx - 0.5 * w
    y_topleft = cy - 0.5 * h
    x_bottomright = cx + 0.5 * w
    y_bottomright = cy + 0.5 * h
    
    box_coords = tf.stack([x_topleft, y_topleft, x_bottomright, y_bottomright], axis=1)
    
    return box_coords

def box_area(boxes):
    """ 
    Helper function used to calculate a bboxes' area given two corners.
    
    Params:
    - boxes: Tensor of shape (N, 4) containing N bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.

    Returns:
    - areas: Tensor of shape (N,) containing the area of each bounding box.
    """
    xmin, ymin, xmax, ymax = tf.split(boxes, 4, axis=1)
    
    # Compute the width and height of each bounding box
    width = tf.squeeze(xmax - xmin, axis=1)
    height = tf.squeeze(ymax - ymin, axis=1)
    
    # Compute the area of each bounding box
    areas = width * height
    
    return areas


def box_iou(box_preds, box_trues):
    """
    Compute the intersection over union (IoU) between pairs of bounding boxes with matching indices.

    Args:
    - box_preds: Tensor of shape (N, 4) containing N predicted bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.
    - box_trues: Tensor of shape (N, 4) containing N ground truth bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.

    Returns:
    - iou: Tensor of shape (N,) containing the IoU between each pair of bounding boxes with matching indices.
    """
    # Compute areas of bounding boxes
    area_preds = box_area(box_preds)
    area_trues = box_area(box_trues)

    # Compute intersection coordinates
    xmin_inter = tf.maximum(box_preds[:, 0], box_trues[:, 0])
    ymin_inter = tf.maximum(box_preds[:, 1], box_trues[:, 1])
    xmax_inter = tf.minimum(box_preds[:, 2], box_trues[:, 2])
    ymax_inter = tf.minimum(box_preds[:, 3], box_trues[:, 3])

    # Compute intersection areas
    width_inter = tf.maximum(0.0, xmax_inter - xmin_inter)
    height_inter = tf.maximum(0.0, ymax_inter - ymin_inter)
    area_inter = width_inter * height_inter

    # Compute union areas
    area_union = area_preds + area_trues - area_inter

    # Compute IoU
    iou = area_inter / area_union

    return iou, area_union

In [37]:
def giou(box_preds, box_trues):
    """
    Calculate the Generalized IoU (GIoU) between all pairs of bounding boxes using TensorFlow.

    Args:
    - box_preds: Tensor of shape (N, 4) containing N bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.
    - box_trues: Tensor of shape (M, 4) containing M bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.

    Returns:
    - giou: Tensor of shape (N, M) containing the Generalized IoU (GIoU) between all pairs of bounding boxes.
    """
    # Expand dimensions to allow broadcasting
    box_preds_expanded = tf.expand_dims(box_preds, axis=1)  # shape: (N, 1, 4)
    box_trues_expanded = tf.expand_dims(box_trues, axis=0)  # shape: (1, M, 4)

    # Compute intersection over union (IoU) and union
    iou = tf.maximum(0.0, tf.minimum(box_preds_expanded[:, :, 2:], box_trues_expanded[:, :, 2:]) - tf.maximum(box_preds_expanded[:, :, :2], box_trues_expanded[:, :, :2]))
    intersection = tf.reduce_prod(iou, axis=-1)  # shape: (N, M)
    area_preds = tf.reduce_prod(box_preds_expanded[:, :, 2:] - box_preds_expanded[:, :, :2], axis=-1)  # shape: (N, 1)
    area_trues = tf.reduce_prod(box_trues_expanded[:, :, 2:] - box_trues_expanded[:, :, :2], axis=-1)  # shape: (1, M)
    union = area_preds + area_trues - intersection  # shape: (N, M)

    # Compute enclosing box (minimum area box that encloses both boxes)
    enclose_min = tf.minimum(box_preds_expanded[:, :, :2], box_trues_expanded[:, :, :2])  # shape: (N, M, 2)
    enclose_max = tf.maximum(box_preds_expanded[:, :, 2:], box_trues_expanded[:, :, 2:])  # shape: (N, M, 2)
    enclose_size = tf.maximum(enclose_max - enclose_min, 0.0)  # shape: (N, M, 2)
    enclose_area = tf.reduce_prod(enclose_size, axis=-1)  # shape: (N, M)

    # Compute Generalized IoU (GIoU)
    giou = intersection / tf.maximum(union, 1e-10) - (enclose_area - union) / tf.maximum(enclose_area, 1e-10)

    return giou

def huber_loss(box_preds, box_trues):
    """
    Compute the Huber loss (smooth-L1) for bounding boxes.

    Parameters:
    - box_preds: Predicted bounding boxes of shape (N, 4) representing (xmin, ymin, xmax, ymax).
    - box_trues: Target bounding boxes of shape (N, 4) representing (xmin, ymin, xmax, ymax).

    Returns:
    - huber_loss: Scalar tensor representing the Huber error (smooth-L1) between the predicted and target bounding boxes.
    """
    loss_fn = tf.keras.losses.Huber()
    huber_loss = loss_fn(box_trues, box_preds)
    
    return huber_loss

def l1_loss(box_preds, box_trues):
    """
    Calculate the L1 loss between all pairs of bounding boxes using TensorFlow.

    Args:
    - box_preds: Tensor of shape (N, 4) containing N bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.
    - box_trues: Tensor of shape (M, 4) containing M bounding boxes in (x_topleft, y_topleft, x_bottomright, y_bottomright) format.

    Returns:
    - loss: Tensor of shape (N, M) containing the L1 loss between all pairs of bounding boxes.
    """
    # Expand dimensions to allow broadcasting
    box_preds_expanded = tf.expand_dims(box_preds, axis=1)  # shape: (N, 1, 4)
    box_trues_expanded = tf.expand_dims(box_trues, axis=0)  # shape: (1, M, 4)

    # Compute L1 loss
    loss = tf.reduce_sum(tf.abs(box_preds_expanded - box_trues_expanded), axis=-1)  # shape: (N, M)

    return loss


def crossentropy_loss(class_preds, class_trues):
    """
    Calculate the cross-entropy loss between all pairs of predicted and true classes using TensorFlow.

    Args:
    - class_preds: Tensor of shape (N, C) containing N sets of class predictions, where C is the number of classes.
    - class_trues: Tensor of shape (M, C) containing M sets of true class labels, where C is the number of classes.

    Returns:
    - loss: Tensor of shape (N, M) containing the cross-entropy loss between all pairs of predicted and true classes.
    """
    # Compute cross-entropy loss

    class_preds = tf.cast(class_preds, dtype=tf.float32)
    class_trues = tf.cast(class_trues, dtype=tf.float32)
    
    # Compute cross-entropy loss
    loss_matrix = -tf.tensordot(class_trues, tf.math.log(class_preds), axes=1)
    
    return loss_matrix




In [7]:
def calculate_loss(box_preds, box_trues):
    pass

In [38]:

def tests():
    box_preds = tf.constant([[1.0, 2.0, 5.0, 6.0], [2.0, 3.0, 6.0, 7.0]])
    box_trues = tf.constant([[3.0, 4.0, 7.0, 8.0], [4.0, 5.0, 8.0, 9.0]])

    class_preds = tf.constant([[0.4, 0.6], [0.9, 0.1]])
    class_trues = tf.constant([[0, 1], [0, 1]])
    
    iou_test = box_iou(box_preds, box_trues)
    print(iou_test[0].numpy()) # printing ious
    print(iou_test[1].numpy()) # printing unions (used for gIoU)
    assert(iou_test[0][0] == 1/7)
    assert(iou_test[0][1] == 1/7) 

    giou_test = giou(box_preds, box_trues)
    print(giou_test)
    assert(tf.round(giou_test[0][0], 5) == tf.round(-5/63, 5))

    huber_test = huber_loss(box_preds, box_trues)
    print(huber_test)
    assert(huber_test == 1.5)

    l1_test = l1_loss(box_preds, box_trues)
    print(l1_test)

    ce_test = crossentropy_loss(class_preds, class_trues)
    print(ce_test)

tests()

[0.14285715 0.14285715]
[28. 28.]
tf.Tensor(
[[-0.07936507 -0.33508888]
 [ 0.31130433 -0.07936507]], shape=(2, 2), dtype=float32)
tf.Tensor(1.5, shape=(), dtype=float32)
tf.Tensor(
[[ 8. 12.]
 [ 4.  8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.10536054 2.3025851 ]
 [0.10536054 2.3025851 ]], shape=(2, 2), dtype=float32)


In [9]:
def np_tf_linear_sum_assignment(matrix):

    indices = linear_sum_assignment(matrix)
    target_indices = indices[0]
    pred_indices = indices[1]

    #print(matrix.shape, target_indices, pred_indices)

    target_selector = np.zeros(matrix.shape[0])
    target_selector[target_indices] = 1
    target_selector = target_selector.astype(np.bool)

    pred_selector = np.zeros(matrix.shape[1])
    pred_selector[pred_indices] = 1
    pred_selector = pred_selector.astype(np.bool)

    #print('target_indices', target_indices)
    #print("pred_indices", pred_indices)

    return [target_indices, pred_indices, target_selector, pred_selector]

In [10]:
def hungarian_matching(t_bbox, t_class, p_bbox, p_class, fcost_class=1, fcost_bbox=5, fcost_giou=2) -> tuple:

    # if slice_preds:
    #     size = tf.cast(t_bbox[0][0], tf.int32)
    #     t_bbox = tf.slice(t_bbox, [1, 0], [size, 4])
    #     t_class = tf.slice(t_class, [1, 0], [size, -1])
    #     t_class = tf.squeeze(t_class, axis=-1)

    # Convert frpm [xc, yc, w, h] to [xmin, ymin, xmax, ymax]
    # p_bbox_xy = bbox.xcycwh_to_xy_min_xy_max(p_bbox)
    # t_bbox_xy = bbox.xcycwh_to_xy_min_xy_max(t_bbox)

    softmax = tf.nn.softmax(p_class)

    # Classification cost for the Hungarian algorithom 
    # On each prediction. We select the prob of the expected class
    cost_class = crossentropy_loss(p_class, t_class)

    # L1 cost for the hungarian algorithm
    cost_bbox = l1_loss(p_bbox, t_bbox)

    # Generalized IOU
    cost_giou = -giou(p_bbox, t_bbox)

    # Final hungarian cost matrix
    cost_matrix = fcost_bbox * cost_bbox + fcost_class * cost_class + fcost_giou * cost_giou

    selectors = tf.numpy_function(np_tf_linear_sum_assignment, [cost_matrix], [tf.int64, tf.int64, tf.bool, tf.bool] )
    target_indices = selectors[0]
    pred_indices = selectors[1]
    target_selector = selectors[2]
    pred_selector = selectors[3]

    return pred_indices, target_indices, pred_selector, target_selector, t_bbox, t_class